### ISSUE TITLE
Playnite not detecting proper Origin install state

### ISSUE THREAD

**Issue by p-engun** [JosefNemec/PlayniteExtensions#31] opened 2021-06-02 15:50 UTC
**Describe the bug**
When attempting to launch origin games (EA) the client only says, "install" and when I change the play action it works until I refresh the library or restart Playnite, at which point it reverts back to me having to press "install" and change the play actions again. I managed to fix this by unchecking everything except "Import installed games" in the Playnite Origin Library.

**To Reproduce**
Steps 1 & 2 only needed if Origin Extension not enabled
1. Launch Playnite
2. Go to Settings > Extensions > Libraries > Origin Library Importer > Enable
3. Settings > Libraries > Origin > Check "Import installed games" and "Connect account"
4. (If you haven't done this prior to reading this) Check "Import not installed games" and Authenticate User.
5. Navigate to any Origin Game > Install
6. Click More > Edit > Actions > Add Play Action > Uncheck "Managed by the library plugin" > Set information as follows:
Type: Executable
Path: Navigate to the game .exe file (This PC > Local Disk (C:) > Program Files (x86) > Origin Games > Game Folder > File name ending in ".exe" (executable))
Arguments: Leave Blank
Working Directory: Leave Blank
7. Press "Save"
8. Run the game (it should launch)
9. Restart Playnite (Playnite logo) > Exit or Playnite Logo > Update Game Library > Update All / Origin
10. The game should appear as uninstalled again, and will not work when you try to launch it (you have to re-do step 6) even if the game is still installed on the system, I managed to fix this issue by navigating to Settings > Libraries > Origin > Unchecking everything except "Import installed games".

**Screenshots**
![image](https://user-images.githubusercontent.com/77411488/120511947-cd473600-c3c2-11eb-8cb2-35dfb8678390.png)
![image](https://user-images.githubusercontent.com/77411488/120512012-d932f800-c3c2-11eb-8fa5-a98315154723.png)

**Diagnostics ID**
69565265-1104-414f-9b52-701aa82c3334 (This is fixed version, to revert to bugged backtrack steps above)

**Comment by j-marcon** [comment] 2021-06-11 18:57
I'm having the same issue here. I've only tested it with Star Wars: Battlefront II that was acquired through the Epic Games Store but is activated on my Origin library. I can confirm that the trick of disconnecting my account works, which would point to the fact that syncing with the account overrides the local installation status of the game. Disconnecting the account is however not a long term solution. Happy to provide more information as needed or even look at writing a fix if someone more familiar with the codebase can point me in the right direction.

**Comment by JosefNemec** [comment] 2021-06-12 08:15
If it only happens with specific games, then try repairing the game install in Origin client or try completely reinstalling Origin. I can't reproduce it myself with either Battlefront II from Epic or BF V from Origin.

**Comment by JosefNemec** [comment] 2021-06-12 08:17
Also, Origin sometimes imports multiple copies of a game (some of them are trial versions) and only some instances might be reporting install state properly. Make sure you didn't remove those working instances and added them to ignore list (you can check in app settings).

**Comment by JosefNemec** [comment] 2021-06-12 08:19
Lastly, see this https://github.com/JosefNemec/Playnite/issues/901#issuecomment-859968364

**Comment by p-engun** [comment] 2021-06-12 15:57
> If it only happens with specific games, then try repairing the game install in Origin client or try completely reinstalling Origin. I can't reproduce it myself with either Battlefront II from Epic or BF V from Origin.

I do not know about Epic, but it happens to me through origin. It is not specific games for me, but every game in my library (about 20 Origin games). You can replicate it by just installing a fresh copy of playnite and adding origin library with every box checked.

**Comment by JosefNemec** [comment] 2021-06-12 16:13
Have you tried reinstalling Origin and repairing game installs in Origin? Because I can't reproduce it.

**Comment by p-engun** [comment] 2021-06-13 18:07
> Have you tried reinstalling Origin and repairing game installs in Origin? Because I can't reproduce it.

Yes I did that originally, I am thinking it might be an external app blocking the instal state, maybe gif your game, geforce experience, wallpaper engine, hp smart, CAM or oculus. @j-marcon if you have any of these programs let me know, they might be common errors. I am thinking startup/ background apps / programs that we both have in common may be the issue

**Comment by j-marcon** [comment] 2021-06-13 18:16
> @j-marcon if you have any of these programs let me know, they might be common errors. I am thinking startup/ background apps / programs that we both have in common may be the issue

Of those you've mentioned, I only have GeForce Experience. And I can't think of anything else I have installed that is video game related other than things like Steam, Origin, Epic Games, etc, obviously.

**Comment by JosefNemec** [comment] 2021-06-13 18:24
Please attach content of `c:\ProgramData\Origin\LocalContent\` directory after you update Origin library in Playnite and also generate new diag. package immediately after the update finishes. Thank you

**Comment by p-engun** [comment] 2021-06-13 18:28
> Please attach content of `c:\ProgramData\Origin\LocalContent\` directory after you update Origin library in Playnite and also generate new diag. package immediately after the update finishes. Thank you

I don't have that file path, I followed C:\Program Files (x86)\Origin and I don't have a LocalContent Folder/ File. I have also looked in my standard Program Files and OriginGames.

**Comment by JosefNemec** [comment] 2021-06-13 18:34
You definitely have that folder there. You may need to enable display of hidden folders in Explorer.

At least `c:\ProgramData\Origin\` must be there. If not, then that's the root issue here, that's where Origin stores all user related data, including what games are installed.

**Comment by j-marcon** [comment] 2021-06-13 19:32
> Please attach content of `c:\ProgramData\Origin\LocalContent\` directory after you update Origin library in Playnite and also generate new diag. package immediately after the update finishes. Thank you

I have STAR WARS Battlefront II/ with:

- map.crc
- Origin.OFR.50.0002015.dat
- Origin.OFR.50.0002015@epic.ddc
- Origin.OFR.50.0002015@epic.mfst
- Origin.OFR.50.0002015@epic.pkg

**Comment by JosefNemec** [comment] 2021-06-13 19:39
Please attach the whole directory (zip it) and also new diag. package I asked for.

**Comment by JosefNemec** [comment] 2021-06-14 07:19
I think I found the issue. Are games not being detected as installed games from either Epic or from EA Play subscription? Do you have some games that you "bought normally"? Those should be detected just fine.

**Comment by JosefNemec** [comment] 2021-06-14 11:51
Please try it with [this debug](https://github.com/JosefNemec/PlayniteExtensions/files/6648056/OriginDebug.zip) version of Origin plugin (unpack to `<playnite install dir>\Extensions\OriginLibrary\`). If it still doesn't work, generate new diagnostics package while using this version of Origin plugin. Thanks

**Comment by p-engun** [comment] 2021-06-14 15:33
> You definitely have that folder there. You may need to enable display of hidden folders in Explorer.
> 
> At least `c:\ProgramData\Origin\` must be there. If not, then that's the root issue here, that's where Origin stores all user related data, including what games are installed.

I did that, but am unsure how to make a .diag file?

**Comment by p-engun** [comment] 2021-06-14 15:33
> Please try it with [this debug](https://github.com/JosefNemec/PlayniteExtensions/files/6648056/OriginDebug.zip) version of Origin plugin (unpack to `<playnite install dir>\Extensions\OriginLibrary\`). If it still doesn't work, generate new diagnostics package while using this version of Origin plugin. Thanks

will try this now

**Comment by p-engun** [comment] 2021-06-14 15:38
> Please try it with [this debug](https://github.com/JosefNemec/PlayniteExtensions/files/6648056/OriginDebug.zip) version of Origin plugin (unpack to `<playnite install dir>\Extensions\OriginLibrary\`). If it still doesn't work, generate new diagnostics package while using this version of Origin plugin. Thanks

Yep that worked. The plugins are auto detecting in the correct install state and are playable

**Comment by j-marcon** [comment] 2021-06-15 02:15
> Please try it with [this debug](https://github.com/JosefNemec/PlayniteExtensions/files/6648056/OriginDebug.zip) version of Origin plugin (unpack to `<playnite install dir>\Extensions\OriginLibrary\`). If it still doesn't work, generate new diagnostics package while using this version of Origin plugin. Thanks

I can confirm it works for me too. Thanks for the fix!

**Comment by JosefNemec** [comment] 2021-06-15 12:39
Fixed in 8.13

**Closed by JosefNemec** 2021-06-15 12:39 UTC
