### ISSUE TITLE
Cannot import "not installed" games from Amazon Games

### ISSUE THREAD

**Issue by to** [JosefNemec/PlayniteExtensions#250] opened 2023-01-22 10:39 UTC
I cannot import "not installed" games from Amazon Prime Gaming.

- "installed games" have been imported successfully.
- I usually use amazon.co.jp and gaming.amazon.com.
- not applying any filters.
- empty Import Exclusion List.
- displaying 'User is authenticated' at Amazon Games/Configure Integrations.
- Amazon Games app is installed on the PC and it work well.
- diagnostics package "082ef9d9-a72a-41c4-8200-4e9f1ef9a839"
- Playnite Ver.10.9 and AmazonGames library integration Ver.2.6

GetAccountEntitlements(AmazonGamesLibrary/Services/AmazonAccountClient.cs) is work properly in Japanese as well? Is there anything that I need to change?

Lastly, I respect and appreciate you for developing such a great software.

**Comment by JosefNemec** [comment] 2023-02-13 09:28
The API returned no games available on your account for some reason. I don't think I will be able to debug this myself, somebody with Japanese Amazon account will have to look into it.

**Comment by TheDarkPreacher** [comment] 2023-03-16 17:59
Having the same issue with my American Amazon account. Not installed games not importing.

**Comment by JosefNemec** [comment] 2023-03-17 14:28
Can't reproduce I'm afraid and plugin already uses American API domain. Go to "About Playnite" menu and generate diag. package for me.

**Comment by TheDarkPreacher** [comment] 2023-04-20 12:59
Any update on this?

**Comment by JosefNemec** [comment] 2023-04-20 13:03
No update. I still can't reproduce it and if it's region specific issue then somebody from that region will have to look into it.

**Comment by masooh** [comment] 2023-09-09 08:29
Hi, I have the same issue with Amazon. Other libraries work fine.

**Diagnostics ID**
15da81e7-1900-4ec6-80b8-415f12194411

**extension.log**
```
09-09 10:19:30.810|DEBUG|AmazonGamesLibrary#AmazonGamesLibrary:Found 1 installed Amazon games.
09-09 10:19:32.470|DEBUG|AmazonGamesLibrary#AmazonGamesLibrary:Found 0 library Amazon games.
```

How can I help to investigate?

_P.S.: Thanks for this amazing app. I was formerly so annoying checking all the game clients one by one._

**Comment by kkhcheng** [comment] 2024-02-29 23:36
Hi I see the same issue today.  diag id: 4cdfe57a-a9a7-4021-9bf3-dcf1bc4a3382

**Comment by JosefNemec** [comment] 2024-07-10 12:39
> No update. I still can't reproduce it and if it's region specific issue then somebody from that region will have to look into it.

Closing per this comment. Code contributions are welcome if somebody can reproduce it with their account and can make a fix for it.

**Closed by JosefNemec** 2024-07-10 12:39 UTC
Labels: bug
