### ISSUE TITLE
Battle.net doesn't show Diablo II: Resurrected

### ISSUE THREAD

**Issue by rhazor** [JosefNemec/PlayniteExtensions#367] opened 2024-02-24 21:47 UTC
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/22996586/0f801ad0-aa37-4a8d-bda1-82e63d2c45d2)
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/22996586/477c574e-39b0-45d0-bba6-adb1d2dd7554)

**Comment by JosefNemec** [comment] 2024-02-24 21:50
Make sure that you have import of installed games enabled and that you don't have a filter enabled to show only uninstalled games.

**Comment by rhazor** [comment] 2024-02-24 22:23
Hi, where is this **_import of installed games_** setting?

I cleared all filters, I did reset settings, I'm authorized and logged in, rescanned/updated libraries, exclusion list is empty.

Using search:

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/22996586/d5444825-cd99-4fe3-9c10-5aeb508b56b2)

**Comment by hawkeye116477** [comment] 2024-02-27 17:23
> where is this import of installed games setting?

In plugin settings.

**Comment by rhazor** [comment] 2024-02-27 17:26
It is ticked
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/22996586/079fb206-79b2-4f90-aa36-e65837fe8710)

**Comment by diogoBRRN** [comment] 2024-04-01 01:54
I'm with the same problem, but with Diablo 1. Looks like can resolve with the same solution because the two games are old, new games aren't happening this (I think).

**Comment by rhazor** [comment] 2024-04-01 08:06
I think that's the reason https://github.com/JosefNemec/PlayniteExtensions/wiki/Battle.net-troubleshooting#authentication-being-lost-after-some-time

![image](https://github.com/JosefNemec/PlayniteExtensions/assets/22996586/cbcd5eab-843e-4d66-b70e-c514e467b7a8)

**Comment by diogoBRRN** [comment] 2024-04-01 10:04
Can be. But Diablo 1 and 2 are new games or are recently published?

**Comment by rhazor** [comment] 2024-04-01 10:08
If I understand, the devs of the battle.net extension has to add games manually or something.

**Comment by shad00m** [comment] 2024-04-20 21:58
I have the exact opposite as a problem. It shows "Diablo II: Resurrected" in Playnite even though I don't own the game.
It's the only wrong game in my list.

**Comment by JosefNemec** [comment] 2024-07-10 12:09
Can't reproduce. The game is importing for me properly in both installed and uninstalled states. Somebody who's able to replicate it would need to debug and fix this. Closing for now.

**Closed by JosefNemec** 2024-07-10 12:09 UTC
Labels: bug
