### ISSUE TITLE
[Steam] Newly Added Games Are "Last Played" on Date Added

### ISSUE THREAD

**Issue by burnpsy** [JosefNemec/PlayniteExtensions#111] opened 2021-10-25 19:03 UTC
**Describe the bug**
Games added via Steam have their last played date set to the date they're added to the library instead of "Never". I have checked all of my other libraries (GOG, Ubisoft, Origin, Battle.net, Epic, etc.), and only Steam has this problem.

**To Reproduce**
Buy a game on Steam and add it to Playnite using the Steam integration.

**Screenshots**
I have attached a screenshot showing my newly-added Marvel's Guardians of the Galaxy preload. It shows today's date as my last played, even though that couldn't possibly be the case since the game doesn't release until tomorrow.
![2021-10-25](https://user-images.githubusercontent.com/6007819/138754311-1f9fb122-3acc-4831-889f-4789ca9c4b3b.png)

**Diagnostics ID**
0bcfbe9d-4540-480f-851c-91c4a94e9ff8

**Comment by JosefNemec** [comment] 2021-10-30 10:58
The issue is that source we use to import last played date is set by Steam even if you just install the game. So the only solution here is either to disable import of last played date completely or accept this issue exists.

**Comment by burnpsy** [comment] 2021-10-30 20:44
Since this problem involves games that have not been played yet, would it not be possible to have it override Steam's last played date if the playtime is zero?

I wouldn't cover every circumstance, but it's certainly better than nothing.

**Comment by burnpsy** [comment] 2021-11-01 21:25
Having poked at this a bit more, I have figured out that games that have never been played but were installed _after_ adding them to Playnite don't update their Last Played in Playnite.

So my earlier suggestion of overriding the last played if playtime is zero seems to resolve most of the issue.

**Comment by JosefNemec** [comment] 2022-01-03 08:34
Fixed in 2.4

**Closed by JosefNemec** 2022-01-03 08:34 UTC
Labels: bug, steam
